### ISSUE TITLE
WebTransport multiaddr format is changing

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p-webtransport#35]
Old:

```
/ip4/123.123.123.123/udp/2498/quic/webtransport/certhash/foo/p2p/QmBar
```

New:

```
/ip4/123.123.123.123/udp/2498/quic-v1/webtransport/certhash/foo/p2p/QmBar
```

The `quic` portion of the WebTransport multiaddr needs to be `quic-v1` as `quic` is for QUIC draft-29 and `quic-v1` is for QUIC version 1 (RFC 9000).  WebTransport is not supposed to support draft-29.

Ref.
- https://github.com/ipfs/kubo/issues/9410
- https://github.com/multiformats/js-multiaddr/pull/294

**Comment by MarcoPolo** [comment]
In the short term, maybe we allow dialing both quic and quic-v1 to support dialing older nodes.
