### ISSUE TITLE
CI: Downgrade Go version

### ISSUE THREAD

**Issue by maschad** [libp2p/js-libp2p-webtransport#67]
These [failures on CI](https://github.com/libp2p/js-libp2p-webtransport/actions/runs/4735329044/jobs/8405568589?pr=66#step:5:100) suggest that the version of quic-go bing used can't be built on Go 1.20 yet. Should we downgrade it to a compatible version?

**Comment by achingbrain** [comment]
This is fixed now but it's almost certainly going to happen again.

Our options are:

1. Update go-libp2p-daemon to the latest libp2p which will give it webtransport support, then we can use a precompiled binary and not have to build the webtransport server in this repo from source - https://github.com/libp2p/go-libp2p-daemon/pull/281
2. Finish the node webtransport listener and remove the go parts of this repo - https://github.com/libp2p/js-libp2p-webtransport/pull/31

My preference is for 2, but 1 might be faster.

**Comment by maschad** [comment]
Seeing as the go-libp2p-daemon's libp2p version is not going to be actively updated by design, I would say that we should invest the effort in 2 as well to remove it as a dependency.

**Comment by p-shahi** [comment]
closing in favor of https://github.com/libp2p/js-libp2p-webtransport/issues/75

**Comment by MarcoPolo** [comment]
Option 3, which is the simplest, is to pin the version of Go.
